name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
      - name: Build Docker image
        run: docker build -t document-matrix .
