name: Update Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-wiki:
    name: Update GitHub Wiki
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Update Wiki
        run: |
          # Check if there are any documentation changes
          if git diff --name-only HEAD~1 | grep -E '\.(md|rst|txt)$'; then
            echo "Documentation changes detected"
            # Copy documentation files to wiki
            cp -r docs/* wiki-repo/ 2>/dev/null || true
            cp README.md wiki-repo/Home.md 2>/dev/null || true
            
            # Commit and push wiki changes
            cd wiki-repo
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            if ! git diff --staged --quiet; then
              git commit -m "Auto-update wiki from main branch"
              git push
              echo "Wiki updated successfully"
            else
              echo "No wiki changes to commit"
            fi
          else
            echo "No documentation changes detected"
          fi
          
      - name: Notify completion
        if: success()
        run: |
          echo "Wiki update process completed"

      - name: Update wiki pages
        run: |
          # Copy wiki files if they exist
          if [ -d "wiki" ]; then
            echo "Copying wiki files..."
            cp -r wiki/* wiki-repo/ 2>/dev/null || echo "No wiki files to copy"
          fi
          
          # Copy additional documentation
          if [ -f "README.md" ]; then
            echo "Copying README as wiki home..."
            cp README.md wiki-repo/Home.md 2>/dev/null || echo "Failed to copy README"
          fi

      - name: Commit and push wiki changes
        run: |
          cd wiki-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, updating wiki..."
            git add .
            git commit -m "Auto-update wiki from main branch [skip ci]"
            git push
            echo "Wiki updated successfully!"
          else
            echo "No changes to wiki files"
          fi
